data_root_dir: /Users/zihua.zeng/Workspace/lama/places_standard_dataset
out_root_dir:  /Users/zihua.zeng/Workspace/lama/experiments/
tb_dir:  /Users/zihua.zeng/Workspace/lama/tb_logs/
pretrained_models:  /Users/zihua.zeng/Workspace/lama/lama/